-- =============================================================================
-- DDL - Estructura de la base de datos
-- Motor: PostgreSQL 16
-- Base de datos: banco_db
--
-- Este script reproduce el esquema que la aplicacion espera encontrar. Equivale
-- al que genera Hibernate a partir de las entidades, escrito de forma explicita
-- para poder versionarlo y ejecutarlo sin depender de ddl-auto.
--
-- Ejecucion:
--   psql -U banco_user -d banco_db -f schema.sql
-- =============================================================================

DROP TABLE IF EXISTS transacciones;
DROP TABLE IF EXISTS productos;
DROP TABLE IF EXISTS clientes;

-- -----------------------------------------------------------------------------
-- CLIENTES
-- -----------------------------------------------------------------------------
CREATE TABLE clientes (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tipo_identificacion   VARCHAR(20)  NOT NULL,
    numero_identificacion VARCHAR(20)  NOT NULL,
    nombres               VARCHAR(100) NOT NULL,
    apellido              VARCHAR(100) NOT NULL,
    correo                VARCHAR(150) NOT NULL,
    fecha_nacimiento      DATE         NOT NULL,
    fecha_creacion        TIMESTAMP(6) NOT NULL,
    fecha_modificacion    TIMESTAMP(6),

    CONSTRAINT clientes_pkey
        PRIMARY KEY (id),
    CONSTRAINT uk_clientes_numero_identificacion
        UNIQUE (numero_identificacion),
    CONSTRAINT clientes_tipo_identificacion_check
        CHECK (tipo_identificacion IN ('CC', 'CE', 'PASAPORTE'))
);

COMMENT ON TABLE clientes IS 'Personas titulares de los productos financieros';
COMMENT ON COLUMN clientes.fecha_modificacion IS 'Nula mientras el cliente no se haya actualizado';

-- -----------------------------------------------------------------------------
-- PRODUCTOS (cuentas de ahorro y corrientes)
-- -----------------------------------------------------------------------------
CREATE TABLE productos (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tipo_cuenta        VARCHAR(20)   NOT NULL,
    numero_cuenta      VARCHAR(10)   NOT NULL,
    estado             VARCHAR(20)   NOT NULL,
    saldo              NUMERIC(19,2) NOT NULL,
    saldo_disponible   NUMERIC(19,2) NOT NULL,
    exenta_gmf         BOOLEAN       NOT NULL,
    cliente_id         BIGINT        NOT NULL,
    fecha_creacion     TIMESTAMP(6)  NOT NULL,
    fecha_modificacion TIMESTAMP(6),

    CONSTRAINT productos_pkey
        PRIMARY KEY (id),
    CONSTRAINT uk_productos_numero_cuenta
        UNIQUE (numero_cuenta),
    CONSTRAINT fk_productos_cliente
        FOREIGN KEY (cliente_id) REFERENCES clientes (id),
    CONSTRAINT productos_tipo_cuenta_check
        CHECK (tipo_cuenta IN ('AHORROS', 'CORRIENTE')),
    CONSTRAINT productos_estado_check
        CHECK (estado IN ('ACTIVA', 'INACTIVA', 'CANCELADA'))
);

-- Acelera la consulta de los productos de un cliente, que es la mas frecuente.
-- La llave foranea por si sola no crea indice en PostgreSQL.
CREATE INDEX idx_productos_cliente_id ON productos (cliente_id);

COMMENT ON TABLE productos IS 'Cuentas de ahorro y corrientes de los clientes';
COMMENT ON COLUMN productos.numero_cuenta IS 'Diez digitos; las de ahorro inician en 53 y las corrientes en 33';
COMMENT ON COLUMN productos.saldo_disponible IS 'Saldo libre de retenciones; hoy coincide siempre con el saldo';

-- -----------------------------------------------------------------------------
-- TRANSACCIONES (movimientos financieros)
--
-- Cada fila es un movimiento sobre una cuenta. Una consignacion o un retiro
-- generan una fila; una transferencia genera dos (el debito del origen y el
-- credito del destino), unidas por el mismo valor en la columna referencia.
-- -----------------------------------------------------------------------------
CREATE TABLE transacciones (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tipo                    VARCHAR(20)   NOT NULL,
    naturaleza              VARCHAR(10)   NOT NULL,
    producto_id             BIGINT        NOT NULL,
    producto_relacionado_id BIGINT,
    monto                   NUMERIC(19,2) NOT NULL,
    saldo_resultante        NUMERIC(19,2) NOT NULL,
    referencia              VARCHAR(36)   NOT NULL,
    descripcion             VARCHAR(200),
    fecha                   TIMESTAMP(6)  NOT NULL,

    CONSTRAINT transacciones_pkey
        PRIMARY KEY (id),
    CONSTRAINT fk_transacciones_producto
        FOREIGN KEY (producto_id) REFERENCES productos (id),
    CONSTRAINT fk_transacciones_producto_relacionado
        FOREIGN KEY (producto_relacionado_id) REFERENCES productos (id),
    CONSTRAINT transacciones_tipo_check
        CHECK (tipo IN ('CONSIGNACION', 'RETIRO', 'TRANSFERENCIA')),
    CONSTRAINT transacciones_naturaleza_check
        CHECK (naturaleza IN ('CREDITO', 'DEBITO'))
);

-- Estado de cuenta: movimientos de un producto.
CREATE INDEX idx_transacciones_producto_id ON transacciones (producto_id);
-- Permite recuperar los dos movimientos de una misma transferencia.
CREATE INDEX idx_transacciones_referencia ON transacciones (referencia);

COMMENT ON TABLE transacciones IS 'Movimientos financieros; registros inmutables';
COMMENT ON COLUMN transacciones.producto_relacionado_id IS 'Cuenta contraparte en una transferencia; nula en consignaciones y retiros';
COMMENT ON COLUMN transacciones.referencia IS 'Identificador que agrupa los movimientos de una misma operacion';
COMMENT ON COLUMN transacciones.saldo_resultante IS 'Saldo de la cuenta despues de aplicar el movimiento';
